easy_admin:
   entities:
       # List the entity class name you want to manage
       - App\Entity\Area
       - App\Entity\Audience
       - App\Entity\Category
       - App\Entity\City
       - App\Entity\Comment
       - App\Entity\Contact
       - App\Entity\Country
       - App\Entity\Days
       - App\Entity\Department
       - App\Entity\Offer
       - App\Entity\Period
       - App\Entity\Poi
       - App\Entity\Price
       - App\Entity\Review
       - App\Entity\Role
       - App\Entity\Tag
       - App\Entity\User
